name: Build Plugin

on: [push, pull_request] # Déclenche la compilation à chaque push ou PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build avec Maven
        run: mvn clean package

      - name: Upload du JAR compilé
        uses: actions/upload-artifact@v4
